_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.9.18
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
architecture:
    value: UNet
dataset:
    value: PH2
epochs:
    value: 20
learning_rate:
    value: 0.001
loss_fn:
    value: BinaryCrossEntropy
optimizer:
    value: Adam
